### ISSUE TITLE
Would this work for Hera to Odin?

### ISSUE THREAD

**Issue by Hedronmx** [jonathanburgossaldivia/upgrade-Elementary-OS-Loki-to-Hera#1]
It would be nice to see if you can upgrade from Hera to Odin once its released.

Do you think this could work?

**Comment by jonathanburgossaldivia** [comment]
we should try once the Odin version comes out, I tried to do something modifying the repositories from Xenial to Focal but it does not work for now, we have to wait

**Comment by Hedronmx** [comment]
Awesome! ill star the project. Thank you

**Comment by jonathanburgossaldivia** [comment]
> Awesome! ill star the project. Thank you

thanks, let's wait for Odin to come out
